name: Run Locust Tests on Commit
on:
  commit:
    branches:
      - main
jobs:
  locust-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Start Flask server
        run: |
          python server.py &
          echo "Waiting for Flask server to start"
          sleep 30
      - name: Start Locust tests
        run: |
          locust -f locustfile.py --users 10000 --spawn-rate 100 --autostart --run-time 2m --autoquit 5 -H http://127.0.0.1:5000
